plugins {
    id "com.android.application"
}

android {
    namespace "nes.android"
    compileSdk 34
    defaultConfig {
        applicationId "nes.android"
        minSdk 26
        targetSdk 34
        versionCode 3
        versionName "0.4.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    sourceSets {
        main {
            java {
                srcDir "../../src/main/java"
                exclude "nes/host/**"
                exclude "nes/selfcheck/**"
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
